spring.application.name=dev

server.port=8080

# Cau hinh PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-silent-frog-azy1kfgl-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_3kTtp5vHlhOn
spring.datasource.driver-class-name=org.postgresql.Driver

# Cau hinh Hibernate / JPA cho PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# TTL cho token login
token.ttl=360000000000